# Cloudflare Pages configuration
name = "nelson-website"
pages_build_output_dir = ".open-next/assets"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXTJS_ENV = "production"
